name: Test TP 4

on:
  pull_request:
    branches:
      - main
    paths:
      - 'TP4/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List directory structure
      run: ls -R

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential flex libfl-dev bison libbison-dev

    - name: Display installed versions
      run: |
        git --version
        make --version
        gcc --version
        flex --version
        bison --version

    - name: Compile code with make
      working-directory: ./TP4
      run: |
        make

    - name: Run test script
      working-directory: ./TP4
      run: |
        chmod +x ./tests/run_testsuite.sh
        ./tests/run_testsuite.sh './bin/tp4'

    - name: Clean up
      working-directory: ./TP4
      run: rm -f ./bin/tp4 ./tests/output/test_*.txt ./tests/output/expected/test_*_clean.txt
